"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, ChevronRight, Landmark, MapPin, Shield, Users } from "lucide-react";
import { AppHeader } from "@/components/navigation/app-header";
import { GeoGlobe } from "@/components/globe/geo-globe";
import { SectionTabs } from "@/components/common/section-tabs";
import { MetricStrip } from "@/components/common/metric-strip";
import { LoadingState, ErrorState } from "@/components/common/states";
import { EconomicChart } from "@/components/charts/economic-chart";
import { TradeChart } from "@/components/charts/trade-chart";
import { NewsFeed } from "@/components/news/news-feed";
import { StatementList } from "@/components/statements/statement-list";
import { Timeline } from "@/components/timeline/timeline";
import { useEntities, useEntity, useNews, useStatements, useTopics } from "@/lib/queries";
import { useGeoStore } from "@/store/use-geo-store";
import type { GeoEntity, NewsArticle, Statement, TimelineEvent, Topic } from "@/types/domain";

const tabs=["Overview","Geopolitics","Topics","News","Statements","Economy","Trade","Timeline","Sources"];
export function CountryExperience({slug}:{slug:string}){const [active,setActive]=useState("Overview");const router=useRouter();const {data:entity,isLoading,isError,refetch}=useEntity(slug);const {data:entities=[]}=useEntities();const {data:topics=[]}=useTopics();const {data:news=[]}=useNews();const {data:statements=[]}=useStatements();const setEntity=useGeoStore(s=>s.setEntity);const setTopic=useGeoStore(s=>s.setTopic);const setRelated=useGeoStore(s=>s.setRelated);useEffect(()=>{if(entity){setEntity(entity.slug,entity.coordinates);setRelated([entity.slug])}},[entity,setEntity,setRelated]);
  if(isLoading)return <Shell><LoadingState/></Shell>;if(isError||!entity)return <Shell><div className="section-pad"><ErrorState retry={()=>refetch()}/></div></Shell>;
  const entityTopics=topics.filter(t=>entity.topicSlugs.includes(t.slug));const entityNews=news.filter(n=>n.entitySlugs.includes(entity.slug));const entityStatements=statements.filter(s=>s.actorSlug===entity.slug||entity.topicSlugs.includes(s.topicSlug));const rels=entity.relationSlugs.map(s=>entities.find(e=>e.slug===s)).filter((item): item is GeoEntity => Boolean(item));
  const openRelation=(other:string)=>router.push(`/relationship/${entity.slug}/${other}`); const syntheticTimeline=(entityTopics[0]?.timeline??[]).map((e,i)=>({...e,id:`${entity.slug}-${i}`,title:i%2===0?`${entity.name}: ${e.title}`:e.title}));
  return <Shell><div className="detail-layout"><div className="detail-map"><GeoGlobe compact controlledEntity={entity.slug} relatedSlugs={[entity.slug]}/></div><article className="detail-scroll"><header className="border-b border-white/10 px-[clamp(22px,4vw,60px)] pb-0 pt-10"><div className="flex items-center gap-2 text-[10px] text-[var(--muted)]"><Link href="/world">World</Link><ChevronRight size={11}/><span>{entity.continent}</span><ChevronRight size={11}/><span>{entity.region}</span></div><div className="mt-8 flex items-end justify-between gap-6"><div><div className="eyebrow">Country / political entity</div><h1 className="mt-3 text-[clamp(2.5rem,5vw,5rem)] font-medium leading-none tracking-[-.06em]">{entity.name}</h1><p className="mt-3 text-sm text-[var(--muted)]">{entity.officialName} · {entity.region}</p></div><div className="mb-1 hidden items-center gap-2 border border-white/10 px-3 py-2 text-[9px] text-[var(--accent)] sm:flex"><MapPin size={11}/>{entity.coordinates.lat.toFixed(2)}°, {entity.coordinates.lng.toFixed(2)}°</div></div><div className="mt-8"><SectionTabs items={tabs} active={active} onChange={setActive}/></div></header><div className="section-pad fade-in" key={active}><CountrySection active={active} entity={entity} topics={entityTopics} news={entityNews.length?entityNews:news.slice(0,5)} statements={entityStatements.length?entityStatements:statements.slice(0,4)} relations={rels} onTopic={(s)=>{const t=topics.find(item=>item.slug===s);if(t){setTopic(t.slug,t.actorSlugs,t.coordinates);router.push(`/topic/${t.slug}`)}}} onRelation={openRelation} timeline={syntheticTimeline}/></div></article></div></Shell>;
}
function Shell({children}:{children:React.ReactNode}){return <div className="app-shell"><AppHeader/><main className="app-main">{children}</main></div>}
function CountrySection({active,entity,topics,news,statements,relations,onTopic,onRelation,timeline}:{active:string;entity:NonNullable<ReturnType<typeof useEntity>["data"]>;topics:Topic[];news:NewsArticle[];statements:Statement[];relations:GeoEntity[];onTopic:(s:string)=>void;onRelation:(s:string)=>void;timeline:TimelineEvent[]}){
  if(active==="Overview")return <><MetricStrip metrics={entity.metrics}/><div className="mt-9 grid gap-10 lg:grid-cols-[1fr_260px]"><div><SectionTitle label="Context" title={`Understanding ${entity.name}`}/><p className="max-w-2xl text-sm leading-7 text-[#b9bfbc]">{entity.context}</p><div className="mt-8"><SectionTitle label="Active agenda" title="Topics shaping the country"/>{topics.map(t=><TopicRow key={t.slug} topic={t} onClick={()=>onTopic(t.slug)}/>)}</div></div><dl className="border-t border-white/10">{[["Capital",entity.capital],["Currency",entity.currency],["Languages",entity.languages.join(", ")],["Government",entity.government],["Region",entity.region]].map(([a,b])=><div key={a} className="border-b border-white/10 py-4"><dt className="eyebrow">{a}</dt><dd className="mt-2 text-xs leading-5">{b}</dd></div>)}</dl></div></>;
  if(active==="Geopolitics")return <><SectionTitle label="Regional position" title="Relationships, memberships, and security"/><p className="max-w-2xl text-sm leading-7 text-[#b9bfbc]">{entity.summary}</p><div className="mt-8 grid gap-px bg-white/10 sm:grid-cols-2">{relations.map(r=><button key={r.slug} onClick={()=>onRelation(r.slug)} className="group flex items-center justify-between bg-[#0b0e11] p-5 text-left hover:bg-[#111519]"><div><div className="text-sm">{r.name}</div><div className="mt-1 text-[10px] text-[var(--muted)]">Bilateral context · Open relationship</div></div><ArrowRight size={14}/></button>)}</div><div className="mt-9 grid gap-6 sm:grid-cols-2"><InfoList icon={<Landmark size={16}/>} label="Memberships" items={entity.memberships}/><InfoList icon={<Shield size={16}/>} label="Security agenda" items={entity.securityIssues}/></div></>;
  if(active==="Topics")return <><SectionTitle label="Connected issues" title={`${entity.name}'s geopolitical topics`}/><div className="mt-6">{topics.map(t=><TopicRow key={t.slug} topic={t} onClick={()=>onTopic(t.slug)}/>)}</div></>;
  if(active==="News")return <><SectionTitle label="News intelligence" title={`Developments connected to ${entity.name}`}/><NewsFeed articles={news}/></>;
  if(active==="Statements")return <><SectionTitle label="Primary-source category" title="Official positions and briefings"/><StatementList statements={statements}/></>;
  if(active==="Economy")return <><SectionTitle label="Economic context" title="Indicators with time and units"/><MetricStrip metrics={entity.metrics}/><div className="mt-7"><EconomicChart series={entity.economy}/></div></>;
  if(active==="Trade")return <><SectionTitle label="Trade relationships" title="Partners and product structure"/><div className="grid gap-5 xl:grid-cols-2"><TradeChart partners={entity.exports} label="Top export partners" onSelect={onRelation}/><TradeChart partners={entity.imports} label="Top import partners" onSelect={onRelation}/></div><div className="mt-6 grid gap-px bg-white/10 sm:grid-cols-2"><InfoList label="Main exports" items={entity.products.exports}/><InfoList label="Main imports" items={entity.products.imports}/></div></>;
  if(active==="Timeline")return <><SectionTitle label="Chronology" title="Geopolitical and diplomatic timeline"/><Timeline events={timeline}/></>;
  return <><SectionTitle label="Provenance" title="Sources and data categories"/><div className="border-t border-white/10">{[["Country geometry","world-atlas and Natural Earth","Country boundaries and physical geography"],["Entity profile","REST Countries and World Bank","Identity, population, currency, and indicators"],["News and images","GDELT and Wikimedia Commons","Source-linked articles with licensed image enrichment"],["Conflict events","UCDP Candidate GED","Parties, dates, locations, and fatality estimates"]].map(([a,b,c])=><div key={a} className="grid gap-2 border-b border-white/10 py-5 sm:grid-cols-[150px_1fr_1fr]"><span className="text-xs">{a}</span><span className="text-xs text-[var(--muted)]">{b}</span><span className="text-[10px] text-[var(--faint)]">{c}</span></div>)}</div></>;
}
export function SectionTitle({label,title}:{label:string;title:string}){return <div className="mb-6"><div className="eyebrow">{label}</div><h2 className="mt-2 text-2xl font-medium tracking-[-.035em]">{title}</h2></div>}
function TopicRow({topic,onClick}:{topic:Topic;onClick:()=>void}){return <button onClick={onClick} className="group grid w-full grid-cols-[8px_1fr_auto] items-center gap-4 border-t border-white/10 py-4 text-left last:border-b"><span className={`h-1.5 w-1.5 rounded-full ${topic.kind==="Conflict"?"bg-[var(--red)]":topic.kind==="Tension"?"bg-[var(--amber)]":"bg-[var(--blue)]"}`}/><span><span className="text-sm group-hover:text-[var(--accent)]">{topic.name}</span><span className="mt-1 block text-[10px] text-[var(--muted)]">{topic.region} · {topic.eyebrow}</span></span><ArrowRight size={13}/></button>}
function InfoList({icon,label,items}:{icon?:React.ReactNode;label:string;items:string[]}){return <div className="bg-[#0d1013] p-5"><div className="mb-4 flex items-center gap-2 text-[var(--accent)]">{icon}<span className="eyebrow">{label}</span></div>{items.map(item=><div key={item} className="flex items-center gap-2 border-t border-white/[.07] py-3 text-xs"><span className="h-1 w-1 rounded-full bg-[var(--faint)]"/>{item}</div>)}</div>}

