"use client";

import { useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, Building2, CircleDot, Globe2, MapPinned } from "lucide-react";
import { AppHeader } from "@/components/navigation/app-header";
import { GeoGlobe } from "@/components/globe/geo-globe";
import { MetricStrip } from "@/components/common/metric-strip";
import { LoadingState, ErrorState } from "@/components/common/states";
import { NewsFeed } from "@/components/news/news-feed";
import { SectionTitle } from "./country-experience";
import { useEntities, useNews, useRegion, useTopics } from "@/lib/queries";
import { geoService } from "@/services/geo-service";
import { useGeoStore } from "@/store/use-geo-store";

export function RegionalExperience({type,slug}:{type:"region"|"continent";slug:string}){const continent=geoService.continents.find(c=>c.slug===slug);const {data:region,isLoading,isError,refetch}=useRegion(type==="region"?slug:"");const {data:entities=[]}=useEntities();const {data:topics=[]}=useTopics();const {data:news=[]}=useNews();const setFocus=useGeoStore(s=>s.setFocus);const router=useRouter();const data=type==="continent"&&continent?{slug:continent.slug,name:continent.name,continent:continent.name,coordinates:continent.coordinates,entitySlugs:entities.filter(e=>e.continent.includes(continent.name)).map(e=>e.slug),topicSlugs:topics.filter(t=>t.actorSlugs.some(a=>entities.find(e=>e.slug===a)?.continent.includes(continent.name))).map(t=>t.slug),summary:`${continent.name} is presented as a connected geopolitical space, with regional organizations, trade corridors, diplomatic networks, and diverse security contexts.`,metrics:[{label:"States / entities",value:continent.entityCount,detail:"Geographic context"},{label:"Active topics",value:String(topics.filter(t=>t.actorSlugs.some(a=>entities.find(e=>e.slug===a)?.continent.includes(continent.name))).length),detail:"Prototype set"},{label:"Regions",value:String(continent.regions.length),detail:"Navigation areas"},{label:"Dataset",value:"Demo",detail:"Level 1"}]}:region;
  useEffect(()=>{if(data)setFocus(data.coordinates,type)},[data?.slug]); if(type==="region"&&isLoading)return <Shell><LoadingState/></Shell>;if(isError||!data)return <Shell><div className="section-pad"><ErrorState retry={()=>refetch()}/></div></Shell>;
  const shownEntities=data.entitySlugs.map(s=>entities.find(e=>e.slug===s)).filter(Boolean);const shownTopics=data.topicSlugs.map(s=>topics.find(t=>t.slug===s)).filter(Boolean);const shownNews=news.filter(n=>n.entitySlugs.some(s=>data.entitySlugs.includes(s)));return <Shell><div className="relative h-[54vh] min-h-[420px] border-b border-white/10"><GeoGlobe controlledTopic={shownTopics[0]?.slug} relatedSlugs={data.entitySlugs}/><div className="absolute bottom-8 left-[clamp(18px,6vw,90px)] z-10 max-w-xl"><div className="eyebrow">{type} · {data.continent}</div><h1 className="mt-3 text-[clamp(3rem,7vw,6rem)] font-medium leading-none tracking-[-.065em]">{data.name}</h1><p className="mt-4 max-w-lg text-sm leading-6 text-[#b5bbb8]">{data.summary}</p></div></div><div className="section-pad"><MetricStrip metrics={data.metrics}/><div className="mt-12 grid gap-12 lg:grid-cols-[1fr_360px]"><div><SectionTitle label="Geographic index" title="Entities in focus"/><div className="grid gap-px bg-white/10 sm:grid-cols-2">{shownEntities.length?shownEntities.map(e=><Link href={`/country/${e!.slug}`} key={e!.slug} className="group flex items-center justify-between bg-[#0b0e11] p-5 hover:bg-[#111519]"><div><div className="text-sm group-hover:text-[var(--accent)]">{e!.name}</div><div className="mt-1 text-[10px] text-[var(--muted)]">{e!.capital} · {e!.region}</div></div><ArrowRight size={13}/></Link>):<div className="col-span-2 bg-[#0b0e11] p-5 text-xs text-[var(--muted)]">Explore globally selectable geometry; rich regional profiles expand in later data levels.</div>}</div><div className="mt-12"><SectionTitle label="Latest context" title="Regional developments"/><NewsFeed articles={shownNews.length?shownNews:news.slice(0,5)} showFilters={false}/></div></div><aside><SectionTitle label="Active agenda" title="Topics"/><div className="border-t border-white/10">{shownTopics.map(t=><button key={t!.slug} onClick={()=>router.push(`/topic/${t!.slug}`)} className="group flex w-full gap-3 border-b border-white/10 py-4 text-left"><span className={`mt-1.5 h-1.5 w-1.5 rounded-full ${t!.kind==="Conflict"?"bg-[var(--red)]":"bg-[var(--blue)]"}`}/><span><span className="text-sm group-hover:text-[var(--accent)]">{t!.name}</span><span className="mono mt-1 block text-[8px] uppercase text-[var(--muted)]">{t!.kind} · {t!.status}</span></span></button>)}</div>{type==="continent"&&continent&&<div className="mt-10"><div className="eyebrow mb-3">Regions</div>{continent.regions.map(name=>{const rSlug=name.toLowerCase().replaceAll(" ","-");const exists=["east-africa","north-africa","middle-east","east-asia","eastern-europe","south-asia"].includes(rSlug);return exists?<Link key={name} href={`/region/${rSlug}`} className="flex items-center gap-2 border-t border-white/10 py-3 text-xs"><MapPinned size={12}/>{name}</Link>:<div key={name} className="flex items-center gap-2 border-t border-white/10 py-3 text-xs text-[var(--muted)]"><CircleDot size={12}/>{name}</div>})}</div>}</aside></div></div></Shell>}
function Shell({children}:{children:React.ReactNode}){return <div className="app-shell"><AppHeader/><main className="app-main">{children}</main></div>}
