"use client";

import { useState } from "react";
import { ArrowUpRight } from "lucide-react";
import type { NewsArticle } from "@/types/domain";
import { DetailDrawer } from "@/components/common/detail-drawer";
import { EmptyState } from "@/components/common/states";

export function NewsFeed({articles,showFilters=true}:{articles:NewsArticle[];showFilters?:boolean}){const categories=["Latest",...Array.from(new Set(articles.map(a=>a.category)))];const [filter,setFilter]=useState("Latest");const [selected,setSelected]=useState<NewsArticle|null>(null);const shown=filter==="Latest"?articles:articles.filter(a=>a.category===filter);return <div>{showFilters&&<div className="mb-4 flex gap-2 overflow-x-auto">{categories.map(c=><button key={c} onClick={()=>setFilter(c)} className={`shrink-0 border px-3 py-1.5 text-[9px] ${filter===c?"border-[var(--accent)]":"border-white/10 text-[var(--muted)]"}`}>{c}</button>)}</div>}{shown.length===0?<EmptyState/>:<div className="border-t border-white/10">{shown.map(article=><button key={article.id} onClick={()=>setSelected(article)} className="group grid w-full grid-cols-[90px_1fr_auto] gap-4 border-b border-white/10 py-5 text-left max-sm:grid-cols-[1fr_auto]"><div className="max-sm:hidden"><div className="mono text-[8px] uppercase text-[var(--accent)]">{article.category}</div><div className="mt-2 text-[9px] text-[var(--faint)]">{article.publishedAt}</div></div><div><h3 className="text-sm leading-5 group-hover:text-[var(--accent)]">{article.headline}</h3><div className="mt-2 text-[10px] text-[var(--muted)]">{article.source} · {article.sourceCountry}<span className="sm:hidden"> · {article.category}</span></div></div><ArrowUpRight size={13} className="mt-1 text-[var(--faint)] group-hover:text-white"/></button>)}</div>}{selected&&<DetailDrawer title={selected.headline} eyebrow={`${selected.source} · ${selected.sourceCountry}`} onClose={()=>setSelected(null)}><div className="flex gap-2"><span className="border border-white/10 px-2 py-1 text-[9px] text-[var(--accent)]">{selected.category}</span><span className="border border-white/10 px-2 py-1 text-[9px] text-[var(--muted)]">{selected.publishedAt}</span></div><p className="mt-6 text-sm leading-7 text-[#c4c9c7]">{selected.summary}</p><div className="mt-8 border-l border-[var(--amber)] pl-4 text-xs leading-5 text-[var(--muted)]">This is fictional prototype reporting, not a live or reproduced news article.</div></DetailDrawer>}</div>}
