"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Filter, MapPin } from "lucide-react";
import { AppHeader } from "@/components/navigation/app-header";
import { GeoGlobe } from "@/components/globe/geo-globe";
import { LoadingState, ErrorState, EmptyState } from "@/components/common/states";
import { useTopics } from "@/lib/queries";
import type { TopicKind } from "@/types/domain";

const filters=["All","Conflict","Tension","Diplomatic","Developing","Economic"] as const;
export function DiscoveryExperience(){const [filter,setFilter]=useState<(typeof filters)[number]>("All");const [hovered,setHovered]=useState<string|null>(null);const {data:topics=[],isLoading,isError,refetch}=useTopics();const shown=filter==="All"?topics:topics.filter(t=>t.kind===filter as TopicKind);return <div className="app-shell"><AppHeader/><main className="app-main"><div className="grid min-h-[calc(100vh-64px)] lg:grid-cols-[minmax(0,1fr)_43%]"><section className="section-pad order-2 lg:order-1"><div className="eyebrow">Topic & conflict discovery</div><h1 className="mt-4 max-w-2xl text-[clamp(2.8rem,6vw,5.5rem)] font-medium leading-[.95] tracking-[-.06em]">The world’s active geopolitical agenda.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-[var(--muted)]">Explore representative conflicts, diplomatic disputes, security questions, and regional relationships through a connected geographic interface.</p><div className="mt-9 flex items-center gap-2 overflow-x-auto pb-2"><Filter size={13} className="mr-1 shrink-0 text-[var(--muted)]"/>{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`shrink-0 border px-3 py-2 text-[9px] ${filter===f?"border-[var(--accent)]":"border-white/10 text-[var(--muted)]"}`}>{f}</button>)}</div>{isLoading?<LoadingState/>:isError?<ErrorState retry={()=>refetch()}/>:shown.length===0?<EmptyState/>:<div className="mt-5 border-t border-white/10">{shown.map((topic,i)=><Link onMouseEnter={()=>setHovered(topic.slug)} onMouseLeave={()=>setHovered(null)} href={`/topic/${topic.slug}`} key={topic.slug} className="group grid grid-cols-[40px_1fr_auto] gap-4 border-b border-white/10 py-5"><span className="mono text-[9px] text-[var(--faint)]">0{i+1}</span><span><span className="flex items-center gap-2"><i className={`h-1.5 w-1.5 rounded-full ${topic.kind==="Conflict"?"bg-[var(--red)]":topic.kind==="Tension"?"bg-[var(--amber)]":topic.kind==="Developing"?"bg-orange-400":"bg-[var(--blue)]"}`}/><b className="text-base font-medium group-hover:text-[var(--accent)]">{topic.name}</b></span><span className="mt-2 flex items-center gap-2 text-[10px] text-[var(--muted)]"><MapPin size={10}/>{topic.region} · {topic.kind} · {topic.status}</span><span className="mt-3 block line-clamp-2 max-w-xl text-xs leading-5 text-[#aeb4b2]">{topic.summary}</span></span><ArrowUpRight size={14}/></Link>)}</div>}</section><aside className="order-1 h-[42vh] min-h-[340px] border-b border-white/10 lg:sticky lg:top-16 lg:order-2 lg:h-[calc(100vh-64px)] lg:border-b-0 lg:border-l"><GeoGlobe compact controlledTopic={hovered??shown[0]?.slug} relatedSlugs={(topics.find(t=>t.slug===hovered)?.actorSlugs)??shown[0]?.actorSlugs}/></aside></div></main></div>}
