"use client";

import { useEffect } from "react";
import Link from "next/link";
import { ArrowLeftRight, ArrowRight } from "lucide-react";
import { AppHeader } from "@/components/navigation/app-header";
import { GeoGlobe } from "@/components/globe/geo-globe";
import { LoadingState, ErrorState } from "@/components/common/states";
import { SectionTitle } from "@/components/geo/country-experience";
import { Timeline } from "@/components/timeline/timeline";
import { TradeChart } from "@/components/charts/trade-chart";
import { NewsFeed } from "@/components/news/news-feed";
import { useEntities, useNews, useRelationship, useTopics } from "@/lib/queries";
import { useGeoStore } from "@/store/use-geo-store";

export function RelationshipExperience({a,b}:{a:string;b:string}){const {data:relationship,isLoading,isError,refetch}=useRelationship(a,b);const {data:entities=[]}=useEntities();const {data:topics=[]}=useTopics();const {data:news=[]}=useNews();const setRelated=useGeoStore(s=>s.setRelated);const one=entities.find(e=>e.slug===a);const two=entities.find(e=>e.slug===b);useEffect(()=>{if(one&&two)setRelated([one.slug,two.slug])},[one,two,setRelated]);if(isLoading)return <Shell><LoadingState/></Shell>;if(isError||!relationship||!one||!two)return <Shell><div className="section-pad"><ErrorState retry={()=>refetch()}/></div></Shell>;const relatedTopics=topics.filter(t=>t.actorSlugs.includes(a)||t.actorSlugs.includes(b));const relatedNews=news.filter(n=>n.entitySlugs.includes(a)&&n.entitySlugs.includes(b));return <Shell><div className="relative h-[48vh] min-h-[380px] border-b border-white/10"><GeoGlobe compact relatedSlugs={[a,b]}/><div className="absolute bottom-8 left-[clamp(18px,6vw,90px)] z-10"><div className="eyebrow">Bilateral relationship · {relationship.status}</div><h1 className="mt-3 text-[clamp(2.5rem,6vw,5.8rem)] font-medium tracking-[-.065em]">{one.name} <span className="text-[var(--faint)]">↔</span> {two.name}</h1></div></div><div className="section-pad"><div className="grid gap-12 lg:grid-cols-[1fr_350px]"><div><SectionTitle label="Overview" title="A connected bilateral profile"/><p className="max-w-2xl text-base leading-8 text-[#bac0bd]">{relationship.summary}</p><div className="mt-9 grid gap-px bg-white/10 sm:grid-cols-2">{relationship.emphasis.map(x=><div key={x} className="bg-[#0b0e11] p-5"><ArrowLeftRight size={14} className="text-[var(--accent)]"/><div className="mt-3 text-sm">{x}</div></div>)}</div><div className="mt-12"><SectionTitle label="Recent developments" title="What is changing"/>{relationship.developments.map((d,i)=><div key={d} className="flex gap-4 border-t border-white/10 py-4"><span className="mono text-[9px] text-[var(--faint)]">0{i+1}</span><span className="text-sm">{d}</span></div>)}</div><div className="mt-12"><SectionTitle label="Timeline" title="Relationship chronology"/><Timeline events={relationship.timeline}/></div></div><aside><SectionTitle label="Trade" title="Commercial context"/><p className="mb-5 text-xs leading-6 text-[var(--muted)]">{relationship.trade}</p><TradeChart partners={one.exports.filter(p=>p.slug!==one.slug).slice(0,5)} onSelect={()=>{}}/><div className="mt-10"><SectionTitle label="Key topics" title="Shared agenda"/>{relatedTopics.slice(0,4).map(t=><Link key={t.slug} href={`/topic/${t.slug}`} className="flex items-center justify-between border-t border-white/10 py-4 text-sm hover:text-[var(--accent)]"><span>{t.name}</span><ArrowRight size={13}/></Link>)}</div></aside></div><div className="mt-16"><SectionTitle label="News coverage" title="Reports mentioning both actors"/><NewsFeed articles={relatedNews.length?relatedNews:news.slice(0,4)} showFilters={false}/></div></div></Shell>}
function Shell({children}:{children:React.ReactNode}){return <div className="app-shell"><AppHeader/><main className="app-main">{children}</main></div>}
